version: '3.8'

services:
  catalogdb:
    image: mongo
    container_name: catalogdb
    ports:
      - "27017:27017"
    networks:
      - backend

  basketdb:
    image: redis
    container_name: basketdb
    ports:
      - "6379:6379"
    networks:
      - backend
    
  discountdb:
    image: postgres
    container_name: discountdb
    environment:
      POSTGRES_PASSWORD: Your_password123
      POSTGRES_DB: DiscountDb
    ports:
      - "5432:5432"
    networks:
      - backend

  catalog.api:
    build:
      context: ./Catalog.API
    ports:
      - "5002:8080"
    depends_on:
      - catalogdb
    networks:
      - backend
   
  basket.api:
    build:
      context: ./Basket.API
    ports:
      - "5003:8080"
    depends_on:
      - basketdb
    networks:
      - backend

  discount.grpc:
    build:
      context: ./Discount.Grpc
    ports:
      - "5004:80"
    depends_on:
      - discountdb
    networks:
      - backend

networks:
  backend:
